/* JP-60 OSHA layer: hazard tags, standards, pre-task safety gates, per-step mapping.
   Scope: 29 CFR 1910 (general industry). Private-sector employers in Illinois are covered by federal OSHA.
   This is a build-specific safety plan, not legal advice and not a substitute for the shop's written programs.
   Verify current regulation text at osha.gov before relying on any citation. */

const OSHA_URL = n => "https://www.osha.gov/laws-regs/regulations/standardnumber/1910/" + n;

/* hazard tags: label, icon (Font Awesome), which standards apply, and the pre-task gate item */
const TAGS = {
  hot:  {label:"Hot work", icon:"fa-fire-flame-curved", std:["252a","157"],
         gate:"Hot-work permit posted for this bay today, fire watch named, combustibles cleared 35 ft or shielded, charged extinguisher in reach."},
  arc:  {label:"Arc / UV", icon:"fa-bolt", std:["133","252b"],
         gate:"Correct helmet or lens shade on, and screens or curtains up so nobody nearby is exposed to the arc."},
  fume: {label:"Weld fume", icon:"fa-smog", std:["252c","1000"],
         gate:"Local exhaust running and aimed at the arc. Base metal is bare steel, with no galvanized, zinc, cadmium or unknown coating at the joint."},
  cr6:  {label:"Hex chromium", icon:"fa-biohazard", std:["1026","134","252c"],
         gate:"Stainless welding: exposure assessment current, local exhaust on, and every welder's medical clearance, fit test and respirator on file."},
  resp: {label:"Respirator", icon:"fa-mask-face", std:["134"],
         gate:"Right respirator and cartridge for the task, fit-tested for this wearer, seal-checked, cartridges in date."},
  noise:{label:"Noise", icon:"fa-volume-high", std:["95"],
         gate:"Hearing protection on for everyone in the bay, including helpers and fire watch."},
  grind:{label:"Abrasive wheels", icon:"fa-gear", std:["215","243"],
         gate:"Guard fitted, side handle on, wheel RPM rating at or above the tool's, wheel inspected for cracks and ring-tested."},
  lift: {label:"Lifting / rigging", icon:"fa-weight-hanging", std:["184","179","178","176"],
         gate:"Load weight known. Hoist, sling or clamp inspected today and rated above the load. Path clear. Operator trained. Nobody under the load."},
  pinch:{label:"Pinch / crush", icon:"fa-hand-fist", std:["212","217","147"],
         gate:"Guards and two-hand controls in place. Pinch points briefed. Power locked out before clearing a jam or servicing."},
  chem: {label:"Chemicals", icon:"fa-flask", std:["1200","151"],
         gate:"SDS for every product at hand and reviewed. Eyewash path clear. Chemical gloves and face protection staged."},
  flam: {label:"Flammables", icon:"fa-fire-burner", std:["106","107"],
         gate:"Flammable liquids in approved containers or cabinet only, rags in a closed metal can, ignition sources out of the area, ventilation on."},
  co:   {label:"Carbon monoxide", icon:"fa-wind", std:["1000","157"],
         gate:"Work is outdoors, at least 10 ft from buildings and combustibles. Never in the shop or an enclosed trailer. Extinguisher and charged hose staged."},
  heat: {label:"Burns / hot metal", icon:"fa-temperature-high", std:["132","138"],
         gate:"High-heat or leather gloves on. Fresh-cut and fresh-welded parts marked HOT. No bare skin near hot steel."},
  cut:  {label:"Sharp edges", icon:"fa-scissors", std:["132","138"],
         gate:"Cut-resistant gloves on. Sharp edges deburred or flagged before handling."},
  elec: {label:"Electrical", icon:"fa-plug", std:["303","334"],
         gate:"Cords, leads and plugs inspected today with no damage. Work clamp on the workpiece. Tag out any damaged tool."},
  gas:  {label:"Gas cylinders", icon:"fa-gas-pump", std:["101"],
         gate:"Cylinders upright and chained, caps on when not in use, away from heat, arcs and sparks."}
};

/* standards: what each means on this build */
const STANDARDS = {
  "252a":{n:"1910.252(a)", t:"Welding, cutting and brazing: fire prevention",
    w:"Move hot work to a safe area where you can. Otherwise clear or shield combustibles within 35 ft, protect openings where sparks can fall, keep fire-extinguishing equipment ready, and use a fire watch during and for at least 30 minutes after the work. The responsible person authorizes the work (the permit)."},
  "252b":{n:"1910.252(b)", t:"Protection of personnel (eyes, clothing, screens)",
    w:"Helmets and hand shields with the correct filter lens, protective clothing suited to the job, and screens or barriers so other workers are shielded from arc rays."},
  "252c":{n:"1910.252(c)", t:"Ventilation and protection in welding",
    w:"Enough ventilation or local exhaust to keep fume below the limits. Special rules for zinc, cadmium, lead, stainless-steel fume and other toxic metals, including respirators where exhaust is not enough."},
  "253":{n:"1910.253", t:"Oxygen-fuel gas welding and cutting",
    w:"Applies if the crew uses oxy-fuel for any cutting or heating. Cylinder handling, regulators, hoses, flashback protection."},
  "254":{n:"1910.254", t:"Arc welding and cutting equipment",
    w:"Welders and plasma cutters must be installed, grounded and maintained correctly. Leads and connectors insulated and in good condition, and operators trained in safe use."},
  "133":{n:"1910.133", t:"Eye and face protection",
    w:"Eye and face protection that meets ANSI Z87.1 wherever there is a flying-particle, molten-metal, chemical or radiation hazard. Side protection where needed."},
  "132":{n:"1910.132", t:"PPE: general requirements",
    w:"The employer does a written workplace hazard assessment, certifies it (who, when, what), provides and pays for the PPE, and trains each worker on when and how to use it."},
  "135":{n:"1910.135", t:"Head protection", w:"Head protection where there is a danger of falling or flying objects or electrical contact."},
  "136":{n:"1910.136", t:"Foot protection", w:"Protective footwear (steel or composite toe) where there is a danger of falling or rolling objects or punctures."},
  "138":{n:"1910.138", t:"Hand protection",
    w:"Select gloves for the specific hazard: heat, cuts, chemicals, abrasion. Wrong gloves are no protection."},
  "134":{n:"1910.134", t:"Respiratory protection",
    w:"If a respirator is required: a written program, medical evaluation before use, fit test before use and yearly, training, and the right respirator for the contaminant."},
  "1026":{n:"1910.1026", t:"Chromium (VI)",
    w:"Welding stainless can generate hexavalent chromium fume. Permissible exposure limit is 5 µg/m³ (8-hr average), with an action level of 2.5 µg/m³. Exposure assessment, engineering controls first, respirators as backup, medical surveillance and training are required once at or above the action level."},
  "1000":{n:"1910.1000", t:"Air contaminants (Table Z-1)",
    w:"Carbon monoxide PEL is 50 ppm (8-hr). Many other airborne exposures have limits here, so use real ventilation, not open doors alone."},
  "95":{n:"1910.95", t:"Occupational noise exposure",
    w:"At 85 dBA over an 8-hr average, a hearing conservation program applies: monitoring, audiometric testing, hearing protectors, training. Grinding, plasma and air arcing are commonly above this."},
  "215":{n:"1910.215", t:"Abrasive wheel machinery",
    w:"Wheel guards sized to the wheel, wheels inspected and ring-tested before mounting, never exceed the wheel's rated speed, and mount wheels correctly with proper flanges and blotters."},
  "243":{n:"1910.243", t:"Guarding of portable powered tools",
    w:"Guards on portable grinders and saws, and tools used only as designed. Portable abrasive wheels: see 1910.243(c)."},
  "242":{n:"1910.242", t:"Hand and portable powered tools", w:"Tools are kept in safe condition. Compressed air for cleaning is limited to 30 psi at the nozzle, with chip guarding."},
  "212":{n:"1910.212", t:"Machine guarding: general requirements",
    w:"Guard point-of-operation hazards, rotating parts and flying chips on saws, drills and similar machines so operators can't reach into the danger zone."},
  "217":{n:"1910.217", t:"Mechanical power presses (includes press brakes)",
    w:"OSHA treats press brakes under this standard. Point-of-operation guarding or presence-sensing devices, two-hand controls where used, inspection and maintenance records, and trained operators."},
  "147":{n:"1910.147", t:"Control of hazardous energy (lockout/tagout)",
    w:"Servicing or clearing jams on machines that can start or move requires an energy-control procedure: lock and tag the energy source, release stored energy, verify zero energy."},
  "176":{n:"1910.176", t:"Handling materials: general",
    w:"Keep aisles and passageways clear and marked. Stack stock so it can't slip, fall or collapse. Provide safe clearance for equipment and loads."},
  "178":{n:"1910.178", t:"Powered industrial trucks (forklifts)",
    w:"Only trained and evaluated operators. Daily pre-use inspection. Never lift people on forks. Know the truck's capacity plate."},
  "179":{n:"1910.179", t:"Overhead and gantry cranes",
    w:"Rated load marked on the crane, inspected before use and on a schedule, operators trained, and nobody under a suspended load."},
  "184":{n:"1910.184", t:"Slings",
    w:"Slings must be inspected each day before use, removed from service if damaged, and used only within the rated capacity for the hitch used. Keep the capacity tag legible."},
  "157":{n:"1910.157", t:"Portable fire extinguishers",
    w:"Extinguishers are provided, mounted, inspected monthly and maintained, annually serviced, and employees trained on use if they are expected to use them. Travel distance to a Class A extinguisher is 75 ft; this plan sets 30 ft near hot work."},
  "151":{n:"1910.151", t:"Medical services and first aid",
    w:"First-aid supplies and trained responders where there is no nearby infirmary. Where corrosive materials are used, suitable facilities for quick drenching or flushing of eyes and body must be provided in the work area for immediate emergency use."},
  "37":{n:"1910.37", t:"Exit routes", w:"Exit routes are clear, unlocked from inside, lit and marked. No material stored in front of exits or extinguishers."},
  "38":{n:"1910.38", t:"Emergency action plans", w:"Written emergency action plan covering reporting, evacuation routes, headcount and who does what. Employees know it."},
  "22":{n:"1910.22", t:"Walking-working surfaces", w:"Floors kept clean, dry where possible, free of hazards. Aisles and passageways clear. Stand mats where wet processes exist."},
  "303":{n:"1910.303", t:"Electrical: general requirements", w:"Electrical equipment is listed, installed per its instructions, with working space kept clear and unused openings closed."},
  "334":{n:"1910.334", t:"Electrical: use of equipment",
    w:"Portable cord-and-plug equipment must be inspected before use, damaged cords removed from service, and ground-fault circuit interrupters used where required by the standard."},
  "101":{n:"1910.101", t:"Compressed gases: general",
    w:"Cylinders are handled and stored per CGA P-1: valves protected, secured upright, stored away from heat, and visually inspected."},
  "106":{n:"1910.106", t:"Flammable liquids",
    w:"Flammable liquids (acetone, paint, thinners) are stored in approved containers and cabinets in limited quantities, and kept away from ignition sources."},
  "107":{n:"1910.107", t:"Spray finishing",
    w:"Spraying flammable finishes needs a ventilated spray booth or room that meets this standard, with no ignition sources near the area and residue controlled."},
  "1200":{n:"1910.1200", t:"Hazard communication",
    w:"Written HazCom program, SDS for every chemical readily accessible, labeled containers, and employee training. Includes paints, solvents, pickling paste, weld cleaner, gases and degreasers."},
  "141":{n:"1910.141", t:"Sanitation", w:"Clean washing facilities and break areas separate from toxic exposure, particularly after handling chromates, lead-bearing paints or pickling chemicals."},
  "1020":{n:"1910.1020", t:"Access to employee exposure and medical records",
    w:"Exposure records and analyses are kept at least 30 years. Medical records are kept for the duration of employment plus 30 years."},
  "1904":{n:"29 CFR 1904", t:"Recording and reporting injuries and illnesses",
    w:"Record work-related injuries and illnesses on the OSHA 300 log, 300A summary and 301 forms. Keep five years. Report a fatality within 8 hours and an inpatient hospitalization, amputation or loss of an eye within 24 hours (1904.39)."}
};

/* extras on top of tag-derived standards, by step id */
const STEP_STD = {
  "01":["252a","157","151","37","38","1200","132"],
  "02":["132"],
  "03":["176","184","1200"],
  "04":["254","242","215","101"],
  "08":["212"],
  "09":["106"],
  "17":["176"],
  "18":["179","178"],
  "19":["176"],
  "24":["1200","141","136"],
  "26":["217","147"],
  "29":["107","106","1200","141"],
  "30":["157"],
  "32":["22"],
  "33":["176","1200"]
};

/* hazard tags per step */
const STEP_TAGS = {
  "01":["hot","elec"],
  "02":[],
  "03":["lift","cut"],
  "04":["hot","arc","grind","elec","gas"],
  "05":["cut"],
  "06":["hot","arc","fume","noise","heat","elec","cut"],
  "07":["hot","arc","fume","noise","heat","cut","grind"],
  "08":["pinch","cut","noise"],
  "09":["grind","noise","flam","cut"],
  "10":["hot","arc","fume","lift","heat"],
  "11":["hot","arc","fume","heat","pinch"],
  "12":["hot","arc","fume","heat"],
  "13":["hot","arc","fume","heat"],
  "14":["hot","arc","fume","grind","noise","heat"],
  "15":["hot","arc","fume","heat","pinch","cut"],
  "16":["hot","arc","fume","noise","heat"],
  "17":["pinch","lift"],
  "18":["lift","hot","arc","fume","heat"],
  "19":["hot","arc","fume","heat","cut","lift"],
  "20":["hot","arc","fume","pinch","heat"],
  "21":["hot","arc","fume","heat","noise"],
  "22":["hot","arc","fume","heat"],
  "23":["hot","arc","fume","heat"],
  "24":["hot","arc","fume","cr6","resp","chem"],
  "25":["cut"],
  "26":["pinch","hot","arc","fume","cut"],
  "27":["grind","noise","cut"],
  "28":["grind","noise","resp","flam"],
  "29":["flam","chem","resp"],
  "30":["co","heat","flam"],
  "31":["co","heat"],
  "32":["heat","pinch"],
  "33":["lift"]
};

/* controls: hierarchy of controls (OSHA/NIOSH) written for this build, by tag */
const CONTROLS = {
  hot:  ["Eliminate: weld in the designated hot-work bay whenever the part can be moved there.","Engineer: screens, fire blankets, sealed floor gaps.","Admin: permit, fire watch, 30-minute post-watch, end-of-day walk-through.","PPE: FR clothing, leather gloves, boots."],
  arc:  ["Engineer: welding curtains and screens around every arc.","Admin: warn the bay before striking an arc.","PPE: helmet shade 10-13 for MIG/TIG, shade 5-8 for plasma, safety glasses underneath."],
  fume: ["Eliminate: reject galvanized, plated and coated material at receiving.","Engineer: fume extractor at the arc, then room ventilation.","Admin: keep your head out of the plume, rotate tasks.","PPE: respirator when exhaust cannot keep exposure down."],
  cr6:  ["Engineer: local exhaust at the arc. Lowest heat input that fuses the joint.","Admin: exposure assessment, restricted area for stainless welding, wash before eating.","PPE: P100 respirator within a written respiratory program."],
  resp: ["Admin: written program, medical evaluation, annual fit test, cartridge change schedule.","PPE: the respirator and cartridge matched to the contaminant (P100 fume, OV paint vapor)."],
  noise:["Engineer: quieter methods and clamped work.","Admin: limit exposure time, post noise areas.","PPE: plugs or muffs (and double protection if the sound is very loud)."],
  grind:["Engineer: wheel guard on, correct flange, work held in a vise or clamped.","Admin: ring-test wheels, match wheel RPM to the tool.","PPE: face shield over glasses, leather gloves, hearing protection."],
  lift: ["Eliminate: don't carry what a hoist can carry.","Engineer: rated hoist, clamps and slings, tag lines, spreader beam.","Admin: weigh and plan the lift, inspect rigging daily, trained operators.","PPE: gloves and steel-toe boots."],
  pinch:["Engineer: guards, two-hand controls, stops and props.","Admin: lockout before servicing, brief the pinch points, one person runs the machine.","PPE: gloves where the guard allows (never with rotating tools)."],
  chem: ["Eliminate/substitute: use the least hazardous product that works.","Engineer: ventilation, secondary containment, eyewash within reach.","Admin: SDS, labels, training, neutralize and dispose per the SDS.","PPE: chemical gloves, face shield, apron."],
  flam: ["Eliminate: no hot work or ignition sources while flammables are open.","Engineer: approved cabinet, spray booth, closed metal can for rags.","Admin: keep quantities small, remove containers at end of shift.","PPE: respirator and nitrile gloves."],
  co:   ["Eliminate: outdoors only, never in the shop.","Engineer: open air, 10 ft from structures, upwind of people.","Admin: charged hose and extinguisher at the pit, someone always attending.","PPE: high-heat gloves and glasses."],
  heat: ["Engineer: HOT markings, steel-topped cooling area.","Admin: wait to cool before handling, no quenching.","PPE: leather or high-heat gloves, long sleeves, boots."],
  cut:  ["Engineer: deburr edges, use clamps and handles.","Admin: carry plate edge-down and flag sharp ends.","PPE: cut-resistant gloves."],
  elec: ["Engineer: grounded and GFCI-protected outlets, intact insulation.","Admin: daily inspection, tag out damaged tools, keep leads off wet floors.","PPE: dry gloves and boots."],
  gas:  ["Engineer: chain cylinders upright, caps on, away from heat and arcs.","Admin: cylinder cart for moves, inspect hoses and regulators.","PPE: gloves and safety glasses."]
};

/* shop-wide checklists */
const PRESHIFT = [
  ["Fire and emergency", [
    "Two charged ABC extinguishers within 30 ft of the weld area, tags in date, gauge in green",
    "Exit routes and extinguishers unobstructed",
    "First-aid kit stocked, eyewash flushed and path clear",
    "Hot-work permit for the bay posted and signed, fire watch named"]],
  ["Machines and tools", [
    "Grinder guards on, wheels undamaged and rated for the tool RPM",
    "Welder, plasma and TIG leads, cables and connectors inspected, no exposed conductor",
    "Cords and plugs on portable tools inspected, damaged ones tagged out",
    "Cold saw, drill, press brake guards in place and working, stops and two-hand controls tested"]],
  ["Lifting and handling", [
    "Hoist, forklift, slings, plate clamps and spreader inspected today, capacity tags legible",
    "Lifting path clear, plate racks stable, no stock leaning",
    "Floor free of cord, scrap and slip hazards"]],
  ["Air and gas", [
    "Fume extraction on, filters not loaded, airflow checked",
    "Gas cylinders upright, chained, capped, valves closed when idle",
    "Flammables in the cabinet, acetone and paint not near hot work, rags in metal can",
    "Spray booth fans and filters working before painting"]],
  ["People", [
    "Toolbox talk held, hazards for today's steps discussed",
    "PPE inspected and available for everyone: lenses, gloves, helmet, hearing, respirator",
    "Respirator wearers have current medical clearance and fit test on file",
    "Anyone impaired, ill or untrained for a task is reassigned. Nobody works alone on hot work."]]
];

const TRAINING = [
  ["Hazard communication and SDS","1910.1200","All crew, before first exposure; when a new hazard is introduced"],
  ["PPE selection, use, limits","1910.132(f)","All crew, before first use, and when the task or PPE changes"],
  ["Hot work and fire watch","1910.252(a) / NFPA 51B","Welders, fitters, fire watch, authorizing lead"],
  ["Respirator program: medical, fit test, use","1910.134","Anyone who wears a respirator. Fit test yearly"],
  ["Chromium (VI) awareness","1910.1026","Anyone welding or grinding stainless, once exposure is at or above the action level"],
  ["Hearing conservation","1910.95","Employees at or above 85 dBA TWA. Audiometry yearly"],
  ["Abrasive wheels and portable tools","1910.215 / 1910.243","Anyone who changes a wheel or uses a grinder"],
  ["Press brake, saw and drill operation","1910.212 / 1910.217","Machine operators"],
  ["Lockout/tagout","1910.147","Authorized and affected employees. Retrain when procedures change"],
  ["Rigging, slings and cranes","1910.184 / 1910.179","Hoist and crane operators, riggers, signalers"],
  ["Powered industrial trucks","1910.178(l)","Forklift operators. Evaluation every 3 years"],
  ["Fire extinguishers","1910.157(g)","Employees expected to use them. Training yearly"],
  ["First aid and burn care","1910.151","Designated responders"],
  ["Emergency action plan and evacuation","1910.38","All crew, at hire and when the plan changes"]
];
